#!flask/bin/python
from flask import Flask, jsonify
from hello_service import *

app = Flask(__name__)


@app.route('/')
def hello_measurement():
    # get device by type or create if none exists
    response = get_sample_devices()
    devices = response.get('managedObjects')
    if len(devices) == 0:
        hello_device = create_managed_object(generate_sample_device())
    else:
        hello_device = devices[0]

    # create sample measurement with random value for device
    measurement = create_measurement(random_measurement_for(hello_device.get('id')))

    # return measurement generated by platform
    return jsonify(measurement)


@app.route('/health')
def health():
    return '{"status":"UP"}'


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80, debug=True)

