#!flask/bin/python
from flask import Flask, jsonify, request
from hello_service import *

app = Flask(__name__)


@app.route('/')
def hello_measurement():
    # get credentials of service user for particular tenant
    auth = get_authorization()

    # get device by type or create if none exists
    response = get_sample_devices(auth)
    devices = response.get('managedObjects')
    if len(devices) == 0:
        hello_device = create_managed_object(generate_sample_device(), auth)
    else:
        hello_device = devices[0]

    # create sample measurement with random value for device
    measurement = create_measurement(random_measurement_for(hello_device.get('id')), auth)

    # return measurement generated by platform
    return jsonify(measurement)


@app.route('/health')
def health():
    return '{"status":"UP"}'


@app.route('/subscriber')
def get_subscriber():
    tenant_id = request.authorization["username"].split('/')[0]
    subscriber = get_subscriber_for(tenant_id)
    return jsonify(subscriber)


def get_authorization():
    # username has form tenant/user
    tenant_id = request.authorization["username"].split('/')[0]
    subscriber = get_subscriber_for(tenant_id)
    auth = base64_credentials(subscriber["tenant"], subscriber["name"], subscriber["password"])
    return auth


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80, debug=True)

