#!/bin/bash
#
# /etc/init.d/cumulocity-agent - startup script for Cumulocity Agent
#
### BEGIN INIT INFO
# Provides:          cumulocity-agent
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Cumulocity Agent.
# Description:       Start Cumulocity Agent.
### END INIT INFO

# Source function library.
# There is no such script on Ubuntu
#. /etc/init.d/functions

DEFAULT_JAVA_HOME=/usr/lib/jvm/default-java

if [ -z "$JAVA_HOME" ] && [ -x $DEFAULT_JAVA_HOME/bin/java ]; then
    export JAVA_HOME=$DEFAULT_JAVA_HOME
fi

if [ -z "$JAVA_HOME" ]; then
    echo "Environment variable JAVA_HOME not set!"
else
    export PATH=$PATH:$JAVA_HOME/bin
fi

# check if Cumulocity Agent is already started
c8y_process_running() {
    ps aux|grep java|grep lx.agent > /dev/null
    RUNNING=$?
}

chome=/usr/share/${project.artifactId}
prog="c8y-agent.sh"

start() {
    c8y_process_running
    if [ $RUNNING -eq 0 ]; then
        echo "Cumulocity Agent process is already running."
    else
        echo $"Starting $prog..."
        cd $chome
        ./$prog &
    fi
}
stop() {
        echo $"Stopping $prog..."
        killall $prog
        pkill -f c8y.lx.agent.Agent
}
status() {
    echo $"Status $prog: "
    c8y_process_running
    if [ "$RUNNING" -eq 0 ]; then
        echo "Cumulocity Agent is running"
        return 0
    else
        echo "There's no Cumulocity Agent process running"
        return 1
    fi
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac

exit $?
