#!/bin/bash
#
# Cumulocity-Agent Startup script
#
# chkconfig: 345 86 14
# description: Cumulocity-Agent component
# processname: java
# pidfile: /var/run/c8y-agent.pid

### BEGIN INIT INFO
# Provides: java
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Cumulocity Agent
### END INIT INFO

# Source function library.
# There is no such script on Ubuntu
#. /etc/init.d/functions


# set JAVA_HOME for Ubuntu/CentOS
JAVA_HOME_UBUNTU=/usr/lib/jvm/default-java
JAVA_HOME_CENTOS=/usr/java/default

if [ -x $JAVA_HOME_UBUNTU/bin/java ]; then
    export JAVA_HOME=$JAVA_HOME_UBUNTU
elif [ -x $JAVA_HOME_CENTOS/bin/java ]; then
    export JAVA_HOME=$JAVA_HOME_CENTOS
fi

if [ -z "$JAVA_HOME" ]; then
    echo -n "Cannot set JAVA_HOME env."
else
    export PATH=$PATH:$JAVA_HOME/bin
fi


# check if Cumulocity Agent is already started
c8y_process_running() {
    ps aux|grep java|grep lx.agent > /dev/null
    RUNNING=$?
}

chome=/usr/share/cumulocity-agent
prog="c8y-agent.sh"

start() {
    c8y_process_running
    if [ $RUNNING -eq 0 ]; then
        echo -n "Cumulocity Agent process is already running."
    else
        echo -n $"Starting $prog: "
        cd $chome
            ./$prog &
        fi
}
stop() {
        echo -n $"Stopping $prog: "
        killall $prog
}
status() {
    echo $"Status $prog: "
    c8y_process_running
    if [ "$RUNNING" -eq 0 ]; then
        echo "Cumulocity Agent is running"
        return 0
    else
        echo "There's no Cumulocity Agent process running"
        return 1
    fi
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac

exit $?
